@host = http://localhost:8080

GET {{host}}/post

###
GET {{host}}/post/116583c2-3f81-46fe-a5a1-89e6304597ba

###
POST {{host}}/post
Content-Type: application/json

{
  "data": {
    "title": "Quisque accumsan dui id nisl tincidunt",
    "author": {
      "id": "user3",
      "name": "User 3"
    },
    "content": "Quisque accumsan dui id nisl tincidunt, non ultrices risus porttitor."
  }
}

###
PUT {{host}}/post/116583c2-3f81-46fe-a5a1-89e6304597ba
Content-Type: application/json

{
  "data": {
    "id": "116583c2-3f81-46fe-a5a1-89e6304597ba",
    "title": "Vivamus",
    "content": "Vivamus id arcu vel erat feugiat convallis."
  }
}

###
GET {{host}}/post/8f7a0014-9efe-46c1-8cbb-8ab12941e7de/comment

###
POST {{host}}/post/8f7a0014-9efe-46c1-8cbb-8ab12941e7de/comment
Content-Type: application/json

{
  "data": {
    "author": {
      "id": "user3",
      "name": "User 3"
    },
    "content": "Quisque accumsan dui id nisl tincidunt, non ultrices risus porttitor."
  }
}

###
PUT {{host}}/post/8f7a0014-9efe-46c1-8cbb-8ab12941e7de/comment/0a12565a-9dd8-454e-aed6-960040c44dc4
Content-Type: application/json

{
  "data": {
    "id": "0a12565a-9dd8-454e-aed6-960040c44dc4",
    "author": {
      "id": "user3",
      "name": "User 3"
    },
    "content": "Vivamus id arcu vel erat feugiat convallis."
  }
}

###
DELETE {{host}}/post/8f7a0014-9efe-46c1-8cbb-8ab12941e7de
Content-Type: application/json

###
DELETE {{host}}/post/116583c2-3f81-46fe-a5a1-89e6304597ba/comment/b4f7cb23-b304-46db-9a87-ea0dd9a61438
Content-Type: application/json