@host = http://localhost:8080

@postId = {{posts.response.body.$[0].id}}

@commentId = {{comments.response.body.$[0].id}}

# @name posts
GET {{host}}/post

###
GET {{host}}/post/{{postId}}

###
POST {{host}}/post
Content-Type: application/json

{
  "title": "Quisque accumsan dui id nisl tincidunt",
  "author": {
    "id": "user3",
    "name": "User 3"
  },
  "content": "Quisque accumsan dui id nisl tincidunt, non ultrices risus porttitor."
}

###
PUT {{host}}/post/{{postId}}
Content-Type: application/json

{
  "title": "Vivamus",
  "content": "Vivamus id arcu vel erat feugiat convallis."
}

###
# @name comments
GET {{host}}/post/{{postId}}/comment

###
POST {{host}}/post/{{postId}}/comment
Content-Type: application/json

{
  "author": {
    "id": "user3",
    "name": "User 3"
  },
  "content": "Quisque accumsan dui id nisl tincidunt, non ultrices risus porttitor."
}

###
PUT {{host}}/post/{{postId}}/comment/{{commentId}}
Content-Type: application/json

{
  "author": {
    "id": "user3",
    "name": "User 3"
  },
  "content": "Vivamus id arcu vel erat feugiat convallis."
}

###
DELETE {{host}}/post/{{postId}}
Content-Type: application/json

###
DELETE {{host}}/post/{{postId}}/comment/{{commentId}}
Content-Type: application/json